package com.digicoffer.lauditor.Invoice.Models;

import java.io.Serializable;
import java.util.ArrayList;

/**
 * InvoiceModel
 *
 * Covers all fields used across:
 *  - GET  /v3/invoice          (list item)
 *  - GET  /v3/invoice/{id}     (detail / edit pre-fill)
 *  - POST /v3/invoice          (create payload)
 *  - PUT  /v3/invoice/{id}     (edit payload)
 *
 * POST payload shape:
 * {
 *   "invoice_code"    : "INV-001848",
 *   "invoice_sequence": 1848,
 *   "firm_gst_no"     : "",
 *   "firm_pan_no"     : "",
 *   "client_gst_no"   : "",
 *   "client_pan_no"   : "",
 *   "name"            : "new logs",
 *   "billto"          : "#146 bd cfvfvv",
 *   "notes"           : "",
 *   "info"            : { "date": "2026-02-18", "duedate": "2026-02-25" },
 *   "invoice_items"   : [{ "name": "sdfds", "unitPrice": "300", "quantity": 1 }],
 *   "currency_code"   : "INR",
 *   "tax_items"       : [{ "tax_type": "Tax",      "amount": 300, "tax": 0 }],
 *   "discounts"       : [{ "discount_type": "Discount", "amount": 300, "discount": 0 }],
 *   "client"          : [{ "id": "...", "type": "consumer" }],
 *   "matters"         : [],
 *   "include_logo"    : true
 * }
 *
 * POST response:
 * { "error": false, "invoice_id": "...", "document_id": "..." }
 */
public class InvoiceModel implements Serializable {

    // ─────────────────────────────────────────────────────────────────────────
    // LIST response fields  (GET /v3/invoice)
    // ─────────────────────────────────────────────────────────────────────────
    private String  id              = "";
    private String  name            = "";   // invoice title / client label
    private String  invoice_no      = "";   // "INV-001848"
    private String  createdby       = "";
    private String  status          = "";   // "raised" | "collected" | "cancelled"
    private String  date            = "";   // create date display  e.g. "Feb 05, 2026"
    private String  dueDate         = "";
    private String  created         = "";
    private boolean isdisabled      = false;
    private String  client_id       = "";
    private String  MatterId       = "";
    private String  MatterName       = "";
    private String matter_type="";
    private String  client_type     = "consumer";
    private String  docid           = "";
    private String  document_status = "";
    private String  rel_id          = "";
    private boolean can_share       = false;

    // ─────────────────────────────────────────────────────────────────────────
    // DETAIL / FORM fields  (GET /v3/invoice/{id}  and  POST/PUT payload)
    // ─────────────────────────────────────────────────────────────────────────

    // Matches "invoice_code" in payload  (auto-generated by server on create)
    private String  invoiceCode     = "";

    // Matches "invoice_sequence"
    private int     invoiceSequence = 0;

    // Firm tax info  → "firm_gst_no", "firm_pan_no"
    private String  firmGstNo       = "";
    private String  firmPanNo       = "";

    // Client tax info  → "client_gst_no", "client_pan_no"
    private String  clientGstNo     = "";
    private String  clientPanNo     = "";

    // Billing address  → "billto"
    private String  billto          = "";

    // Notes / additional details  → "notes"
    private String  notes           = "";

    // info block  → "info": { "date": "yyyy-MM-dd", "duedate": "yyyy-MM-dd" }
    // Re-uses the "date" and "dueDate" fields from the list model above.
    // On detail response the dates come from info.date / info.duedate (API format)

    // Line items  → "invoice_items"
    private ArrayList<LineItemModel> lineItems = new ArrayList<>();

    // Currency  → "currency_code"
    private String  currencyCode    = "INR";

    // Tax  → "tax_items[0].tax"
    private double  taxAmount       = 0;

    // Discount  → "discounts[0].discount"
    private double  discountAmount  = 0;

    // Logo flag  → "include_logo"
    private boolean includeLogo     = true;

    // POST response fields (populated after successful create)
    private String  invoiceId       = "";   // "invoice_id" from response
    private String  documentId      = "";   // "document_id" from response

    // ─────────────────────────────────────────────────────────────────────────
    // Constructors
    // ─────────────────────────────────────────────────────────────────────────

    public InvoiceModel() {}

    public String getMatter_type() {
        return matter_type;
    }

    public void setMatter_type(String matter_type) {
        this.matter_type = matter_type;
    }
// ─────────────────────────────────────────────────────────────────────────
    // Getters — LIST fields
    // ─────────────────────────────────────────────────────────────────────────

    public String  getId()              { return id; }
    public String  getName()            { return name; }
    public String  getInvoice_no()      { return invoice_no; }
    public String  getCreatedby()       { return createdby; }
    public String  getStatus()          { return status; }
    public String  getDate()            { return date; }
    public String  getDueDate()         { return dueDate; }
    public String  getCreated()         { return created; }
    public boolean isIsdisabled()       { return isdisabled; }
    public String  getClient_id()       { return client_id; }
    public String  getMatterId()       { return MatterId; }
    public String  getClient_type()     { return client_type; }
    public String  getDocid()           { return docid; }
    public String  getDocument_status() { return document_status; }
    public String  getRel_id()          { return rel_id; }
    public boolean isCan_share()        { return can_share; }
    public String  getMatterName()       { return MatterName; }
    // ─────────────────────────────────────────────────────────────────────────
    // Setters — LIST fields
    // ─────────────────────────────────────────────────────────────────────────
    public void setMatterName(String matterName)                    { this.MatterName            = matterName; }
    public void setId(String id)                        { this.id              = id; }
    public void setName(String name)                    { this.name            = name; }
    public void setInvoice_no(String invoice_no)        { this.invoice_no      = invoice_no; }
    public void setCreatedby(String createdby)          { this.createdby       = createdby; }
    public void setStatus(String status)                { this.status          = status; }
    public void setDate(String date)                    { this.date            = date; }
    public void setDueDate(String dueDate)              { this.dueDate         = dueDate; }
    public void setCreated(String created)              { this.created         = created; }
    public void setIsdisabled(boolean isdisabled)       { this.isdisabled      = isdisabled; }
    public void setClient_id(String client_id)          { this.client_id       = client_id; }
    public void setMatterId(String matterId)          { this.MatterId       = matterId; }

    public void setClient_type(String client_type)      { this.client_type     = client_type; }
    public void setDocid(String docid)                  { this.docid           = docid; }
    public void setDocument_status(String s)            { this.document_status = s; }
    public void setRel_id(String rel_id)                { this.rel_id          = rel_id; }
    public void setCan_share(boolean can_share)         { this.can_share       = can_share; }

    // ─────────────────────────────────────────────────────────────────────────
    // Getters — DETAIL / FORM fields
    // ─────────────────────────────────────────────────────────────────────────

    public String  getInvoiceCode()                   { return invoiceCode; }
    public int     getInvoiceSequence()               { return invoiceSequence; }
    public String  getFirmGstNo()                     { return firmGstNo; }
    public String  getFirmPanNo()                     { return firmPanNo; }
    public String  getClientGstNo()                   { return clientGstNo; }
    public String  getClientPanNo()                   { return clientPanNo; }
    public String  getBillto()                        { return billto; }
    public String  getNotes()                         { return notes; }
    public ArrayList<LineItemModel> getLineItems()    { return lineItems; }
    public String  getCurrencyCode()                  { return currencyCode; }
    public double  getTaxAmount()                     { return taxAmount; }
    public double  getDiscountAmount()                { return discountAmount; }
    public boolean isIncludeLogo()                    { return includeLogo; }
    public String  getInvoiceId()                     { return invoiceId; }
    public String  getDocumentId()                    { return documentId; }
    private String logoUrl = "";
    public String getLogoUrl() { return logoUrl != null ? logoUrl : ""; }
    public void setLogoUrl(String logoUrl) { this.logoUrl = logoUrl != null ? logoUrl : ""; }

    // ─────────────────────────────────────────────────────────────────────────
    // Setters — DETAIL / FORM fields
    // ─────────────────────────────────────────────────────────────────────────

    public void setInvoiceCode(String invoiceCode)              { this.invoiceCode     = invoiceCode; }
    public void setInvoiceSequence(int invoiceSequence)         { this.invoiceSequence = invoiceSequence; }
    public void setFirmGstNo(String firmGstNo)                  { this.firmGstNo       = firmGstNo; }
    public void setFirmPanNo(String firmPanNo)                  { this.firmPanNo       = firmPanNo; }
    public void setClientGstNo(String clientGstNo)              { this.clientGstNo     = clientGstNo; }
    public void setClientPanNo(String clientPanNo)              { this.clientPanNo     = clientPanNo; }
    public void setBillto(String billto)                        { this.billto          = billto; }
    public void setNotes(String notes)                          { this.notes           = notes; }
    public void setLineItems(ArrayList<LineItemModel> lineItems){ this.lineItems        = lineItems; }
    public void setCurrencyCode(String currencyCode)            { this.currencyCode    = currencyCode; }
    public void setTaxAmount(double taxAmount)                  { this.taxAmount       = taxAmount; }
    public void setDiscountAmount(double discountAmount)        { this.discountAmount  = discountAmount; }
    public void setIncludeLogo(boolean includeLogo)             { this.includeLogo     = includeLogo; }
    public void setInvoiceId(String invoiceId)                  { this.invoiceId       = invoiceId; }
    public void setDocumentId(String documentId)                { this.documentId      = documentId; }
}