buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 21
        compileSdkVersion = 36
        targetSdkVersion = 36
        ndkVersion = "25.2.9519653"
    }

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.6.1'
        classpath "de.undercouch:gradle-download-task:5.6.0"
        classpath 'com.google.gms:google-services:4.4.4'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.2.0"
        classpath "org.jetbrains.kotlin:compose-compiler-gradle-plugin:2.2.0"
    }
}